### ISSUE TITLE
Mergin plugin tests (2021.4.3) 

### ISSUE THREAD

**Issue by PatrikMizera** [lutraconsulting/qgis-mergin-plugin-manual-tests#14]
## Mergin plugin test plan

| Test environment  | Value |
|---|---|
| Mergin Version:  | 2021.10 |
| Mergin URL: <>  | dev.dev.cloudmergin.com |
|  QGIS Version: |  3.16.3 LTR  |
|  Mergin plugin Version: | 2021.4.3. |
| Date of Execution: | 19.11.2021 |
| Host OS: | Windows 10.0.19042 |

---

### Test Cases
Full version (dev.dev)
- [x] ( #1 ) TC 01: Installation 
- [x] ( #2 ) TC 02: Configuration
- [x] ( #3 ) TC 03: New project
- [x] ( #4 ) TC 04: Project management
    - missing "Tree survey.qgs" in project status
- [x] ( #5 ) TC 05: Project permissions 
- [x] ( #6 ) TC 06: Project tree
- [x] ( #12 ) TC 07: Platforms
- [x] ( #13 ) TC 08: Action banner

Community version (core.dev)
- [x] ( #1 ) TC 01: Installation 
- [x] ( #2 ) TC 02: Configuration
- [x] ( #3 ) TC 03: New project
- [x] ( #4 ) TC 04: Project management 
- [x] ( #5 ) TC 05: Project permissions 
- [x] ( #6 ) TC 06: Project tree
- [x] ( #12 ) TC 07: Platforms
- [x] ( #13 ) TC 08: Action banner
    - TC 04 - TC 07 unfinished due to missing tree template 
    - TC 08 - unable to access admin 
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | 0 |

**Success**
