### ISSUE TITLE
Mergin plugin test plan 

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/qgis-mergin-plugin-manual-tests#8]
## Mergin plugin test plan

| Test environment  | Value |
|---|---|
| Mergin Version:  |  |
| Mergin URL: <>  |  |
|  QGIS Version: |    |
|  Mergin plugin Version: |  |
| Date of Execution: |  |
---

### Test Cases
Full version (dev.dev)
- [ ] ( #1 ) TC 01: Installation 
- [ ] ( #15 ) TC 02: Configuration
- [ ] ( #3 ) TC 03: New project
- [ ] ( #4 ) TC 04: Project management 
- [ ] ( #5 ) TC 05: Project permissions 
- [ ] ( #6 ) TC 06: Project tree
- [ ] ( #12 ) TC 07: Platforms
- [ ] ( #13 ) TC 08: Action banner

Community version (core.dev) - just smoke test is needed here
- [ ] ( #4 ) TC 04: Project management 
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | |

**Success** / **Bugs Created** (erase one)
